Fix TypeScript Build and Update npm Dependencies
    - Update all packages to latest stable version
    - Migrate typings.json to recent schema
    - Fix angular2 error TS2661: Cannot export 'Promise'

This frontend prototype is probably lost, due to deprecated angular and
typings dependencies.